Api example postman
CognitiveScale/cortex-fabric-examples pull request #23
Opened 2020-10-07 20:45 UTC by smichalski-cs

This content supports the docs PR for `reference/rest-api.md`

2020-10-07 21:02 UTC, clee-cs approved these changes

2020-10-07 22:50 UTC, mburpo-CS requested changes
* please add a readme.md at the root of the new APIExamples folder that briefly describes what's in this folder and how to use it
* update the root-level readme.md `contents` section to add this example and give a brief description of it

2020-10-08 22:17 UTC, mburpo-CS commented on APIExamples/README.md
> +</Alert>
need to delete this trailing `</Alert>` (probably copied over from the docusaurus content)

2020-10-09 16:56 UTC, mburpo-CS commented on APIExamples/README.md
> +2. You must set the environment URL to your DCI instance and [your JWT token](/getting-started/access.md) in the example environment file.
`[your JWT token](/getting-started/access.md)` --> this needs to be a full link to the outside cortex-fabric site: https://cognitivescale.github.io/cortex-fabric/docs/getting-started/access/

2020-10-09 17:11 UTC, mburpo-CS approved these changes

2020-10-09 17:12 UTC, merged